#!/bin/bash
#
# run
#
# Start flask server in development mode

# Stop on errors, print commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

FLASK_APP=app.py FLASK_ENV=development flask run